import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ApiClientError, ownerApi } from '../lib/api'
import { clearAuth, getStoredUser, getAuthToken } from '../lib/auth'
import type { BusinessSettings, OwnerDashboard, OwnerNotification, Plan, Subscription, BillingHistoryItem, SocialLink, AdvancedAnalytics } from '../types/api'

const money=(p:number)=>`₹${(p/100).toLocaleString('en-IN')}/mo`
const fmt=(d:string)=>new Date(d).toLocaleString()
function Stat({label,value}:{label:string;value:string|number}){return <div className="owner-stat"><span>{label}</span><strong>{value}</strong></div>}
export function OwnerDashboardPage(){
 const nav=useNavigate(); const user=getStoredUser(); const [tab,setTab]=useState('overview'); const [days,setDays]=useState(30); const [dash,setDash]=useState<OwnerDashboard|null>(null); const [notes,setNotes]=useState<OwnerNotification[]>([]); const [settings,setSettings]=useState<BusinessSettings|null>(null); const [plans,setPlans]=useState<Plan[]>([]); const [sub,setSub]=useState<Subscription|null>(null); const [history,setHistory]=useState<BillingHistoryItem[]>([]); const [links,setLinks]=useState<SocialLink[]>([]); const [advanced,setAdvanced]=useState<AdvancedAnalytics|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 useEffect(()=>{ if(!user||user.role!=='BUSINESS_OWNER'){nav('/login',{replace:true});return} void load() },[days])
 async function load(){setError('');try{const [d,n,s,p,h,l,a]=await Promise.all([ownerApi.dashboard(days),ownerApi.notifications(),ownerApi.settings(),ownerApi.plans(),ownerApi.history(),ownerApi.socialLinks(),ownerApi.advancedAnalytics(days)]);setDash(d);setNotes(n.items);setSettings(s);setPlans(p);setSub(await ownerApi.subscription());setHistory(h);setLinks(l);setAdvanced(a)}catch(e){if(e instanceof ApiClientError)setError(e.message);else setError('Unable to load owner dashboard.')}}
 async function save(kind:'profile'|'branding'|'reviews'){if(!settings)return;setBusy(true);try{if(kind==='profile')await ownerApi.profile({name:settings.name,description:settings.description,category:settings.category,logo_url:settings.logo_url,welcome_message:settings.welcome_message});if(kind==='branding')await ownerApi.branding({brand_primary_color:settings.brand_primary_color,brand_secondary_color:settings.brand_secondary_color});if(kind==='reviews')await ownerApi.reviews({prefer_ai_comments:settings.prefer_ai_comments,google_review_pc_url:settings.google_review_pc_url,google_review_mob_url:settings.google_review_mob_url,nfc_enabled:settings.nfc_enabled,qr_enabled:settings.qr_enabled,customer_settings:settings.customer_settings});await load()}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
 async function downloadReport(format:'csv'|'xlsx'|'pdf'){const token=getAuthToken();if(!token)return;const res=await fetch(ownerApi.exportUrl(format,days),{headers:{Authorization:`Bearer ${token}`}});if(!res.ok){setError('Unable to download report.');return}const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`reviewagentai-${days}d.${format}`;a.click();URL.revokeObjectURL(url)}
 async function buy(plan:string){setBusy(true);try{const order=await ownerApi.checkout(plan);await ownerApi.confirm(order.payment_id,true);await load();setTab('billing')}catch(e){setError(e instanceof Error?e.message:'Billing failed')}finally{setBusy(false)}}
 if(!user)return null
 return <main className="owner-page"><div className="owner-shell"><header className="owner-header"><div><div className="ra-eyebrow">ReviewAgentAI · Owner Console</div><h1>{dash?.business_name||'Business dashboard'}</h1><p>Manage reviews, customer feedback, notifications, billing and your customer experience.</p></div><button className="ra-button ra-button-secondary" onClick={()=>{clearAuth();nav('/login')}}>Sign out</button></header>
 {error&&<div className="owner-error">{error}</div>}
 <nav className="owner-tabs">{[['overview','Overview'],['inbox','Feedback inbox'],['settings','Business settings'],['billing','Billing']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</nav>
 {tab==='overview'&&dash&&<><div className="owner-toolbar"><strong>Performance</strong><select value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90,365].map(x=><option key={x} value={x}>{x} days</option>)}</select></div><div className="owner-stats"><Stat label="Landing views" value={dash.analytics.landing_page_views}/><Stat label="Ratings" value={dash.analytics.rating_selections}/><Stat label="AI reviews" value={dash.analytics.ai_reviews_generated}/><Stat label="Google handoffs" value={dash.analytics.google_handoffs}/><Stat label="Private feedback" value={dash.analytics.private_feedback_submitted}/><Stat label="Social clicks" value={dash.analytics.social_link_clicks}/></div><section className="owner-card"><div className="owner-card-head"><div><h2>Advanced analytics</h2><p>Deeper performance metrics and downloadable reports</p></div><div className="owner-actions"><button className="ra-button ra-button-secondary" onClick={()=>void downloadReport('csv')}>CSV</button><button className="ra-button ra-button-secondary" onClick={()=>void downloadReport('xlsx')}>Excel</button><button className="ra-button ra-button-secondary" onClick={()=>void downloadReport('pdf')}>PDF</button></div></div>{advanced&&<div className="owner-stats"><Stat label="Positive ratio" value={`${advanced.positive_ratio}%`}/><Stat label="Negative ratio" value={`${advanced.negative_ratio}%`}/><Stat label="Complaints" value={advanced.complaints}/><Stat label="AI usage" value={advanced.ai_usage}/><Stat label="Fallback usage" value={advanced.fallback_usage}/><Stat label="Google handoff" value={`${advanced.google_handoff_rate}%`}/></div>}</section><section className="owner-card"><div className="owner-card-head"><div><h2>Rating distribution</h2><p>Last {days} days</p></div><strong>{dash.analytics.google_handoff_rate.toFixed(1)}% handoff rate</strong></div><div className="rating-bars">{['1','2','3','4','5'].map(r=><div key={r}><span>{r} ★</span><div><i style={{width:`${Math.min(100,(dash.analytics.rating_counts[r]||0)*10)}%`}}/></div><b>{dash.analytics.rating_counts[r]||0}</b></div>)}</div></section><section className="owner-card"><div className="owner-card-head"><h2>Recent private feedback</h2><button className="ra-button ra-button-secondary" onClick={()=>setTab('inbox')}>Open inbox</button></div>{dash.recent_complaints.length?<div className="owner-list">{dash.recent_complaints.slice(0,5).map(c=><div className="owner-list-row" key={c.id}><div><b>{c.rating} ★ · {c.status}</b><p>{c.comments}</p></div><small>{fmt(c.created_at)}</small></div>)}</div>:<p className="muted">No private feedback yet.</p>}</section></>}
 {tab==='inbox'&&<section className="owner-card"><div className="owner-card-head"><div><h2>Feedback inbox</h2><p>{notes.length} recent notifications</p></div></div>{notes.length?<div className="owner-list">{notes.map(n=><div className="owner-list-row" key={n.id}><div><span className={`status status-${n.status.toLowerCase()}`}>{n.status}</span><b>{n.type}</b><p>{n.message}</p>{n.complaint_id&&<select value={n.complaint_status||'NEW'} onChange={async e=>{await ownerApi.complaintStatus(n.complaint_id!,e.target.value);await load()}}><option>NEW</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>CLOSED</option></select>}</div><small>{fmt(n.created_at)}</small></div>)}</div>:<p className="muted">Your inbox is clear.</p>}</section>}
 {tab==='settings'&&settings&&<div className="settings-grid"><section className="owner-card"><h2>Business profile</h2><label>Name<input className="ra-input" value={settings.name} onChange={e=>setSettings({...settings,name:e.target.value})}/></label><label>Category<input className="ra-input" value={settings.category||''} onChange={e=>setSettings({...settings,category:e.target.value})}/></label><label>Description<textarea className="ra-input" value={settings.description||''} onChange={e=>setSettings({...settings,description:e.target.value})}/></label><label>Logo URL<input className="ra-input" value={settings.logo_url||''} onChange={e=>setSettings({...settings,logo_url:e.target.value||null})}/></label><label>Welcome message<textarea className="ra-input" value={settings.welcome_message||''} onChange={e=>setSettings({...settings,welcome_message:e.target.value||null})}/></label><button disabled={busy} className="ra-button ra-button-primary" onClick={()=>save('profile')}>Save profile</button></section><section className="owner-card"><h2>Brand & review settings</h2><label>Primary color<input className="ra-input" type="color" value={settings.brand_primary_color} onChange={e=>setSettings({...settings,brand_primary_color:e.target.value})}/></label><label>Secondary color<input className="ra-input" type="color" value={settings.brand_secondary_color} onChange={e=>setSettings({...settings,brand_secondary_color:e.target.value})}/></label><label>Google PC URL<input className="ra-input" value={settings.google_review_pc_url} onChange={e=>setSettings({...settings,google_review_pc_url:e.target.value})}/></label><label>Google mobile URL<input className="ra-input" value={settings.google_review_mob_url} onChange={e=>setSettings({...settings,google_review_mob_url:e.target.value})}/></label><label className="check-line"><input type="checkbox" checked={settings.prefer_ai_comments} onChange={e=>setSettings({...settings,prefer_ai_comments:e.target.checked})}/> Prefer AI-generated comments</label><label className="check-line"><input type="checkbox" checked={settings.nfc_enabled} onChange={e=>setSettings({...settings,nfc_enabled:e.target.checked})}/> NFC enabled</label><label className="check-line"><input type="checkbox" checked={settings.qr_enabled} onChange={e=>setSettings({...settings,qr_enabled:e.target.checked})}/> QR enabled</label><button disabled={busy} className="ra-button ra-button-primary" onClick={()=>save('branding')}>Save branding</button><button disabled={busy} className="ra-button ra-button-secondary" onClick={()=>save('reviews')}>Save review settings</button></section></div>}
 {tab==='billing'&&<><section className="owner-card"><div className="owner-card-head"><div><h2>Subscription</h2><p>{sub?.status} · {sub?.plan}</p></div>{sub?.cancel_at_period_end&&<span className="status status-failed">Cancellation scheduled</span>}</div><div className="plan-grid">{plans.map(p=><div className={`plan-card ${sub?.plan===p.code?'current':''}`} key={p.code}><h3>{p.name}</h3><strong>{money(p.price_paise)}</strong><p>{p.monthly_review_limit} AI review generations/month</p><button disabled={busy||sub?.plan===p.code} className="ra-button ra-button-primary" onClick={()=>buy(p.code)}>{sub?.plan===p.code?'Current plan':'Choose plan'}</button></div>)}</div><button className="ra-button ra-button-secondary" onClick={async()=>{await ownerApi.cancel();await load()}}>Cancel at period end</button></section><section className="owner-card"><h2>Billing history</h2>{history.length?<div className="owner-list">{history.map(h=><div className="owner-list-row" key={h.id}><div><b>{h.plan} · {h.status}</b><p>{money(h.amount_paise)} · Receipt {h.receipt_reference}</p></div><small>{fmt(h.created_at)}</small></div>)}</div>:<p className="muted">No payments yet.</p>}</section></>}
 </div></main>
}
